version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: |
            apt-get update && apt-get install jq zip -y
            apt-get update && apt-get install -yq libgconf-2-4
            apt-get update && apt-get install -y wget --no-install-recommends
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            apt-get update && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM dependencies
          command: |
            if [ ! -f yarn.lock ]; then
              npm install
            else
              yarn install
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Pack
          command: |
            bash .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/dist
      - store_artifacts:
          path: ~/repo/build
      - deploy:
          name: Deploy to Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${NETLIFY_KEY}" != "" ]; then
              bash .circleci/deploy.sh
            else
              echo "Skipping deploy either because this is not the master branch or NETLIFY_KEY is not set"
            fi
